alias nr="npm run"
alias nrb="npm run build"
alias nrbl="npm run build:lib"
alias nrt="npm run test"
alias nrtw="npm runtest:watch"
alias nrd="npm run dev"
alias nrsd="npm run start:dev"

alias ni="npm install"
alias nu="npm uninstall"
