apiVersion: v1
kind: Pod
metadata:
  name: nginx-w-secrets
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name:  MI_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: MI_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password