kind: ConfigMap
apiVersion: v1
metadata:
  name: game-demo
  namespace: default
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  
  game.properties:
    enemy.types=aliens,mosters
    player.maximun-lives=5
  user-interface.properties:
    color.good=purple
    color.bad=yellow
    allow.textmode=true